import '../styles/globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Navbar from '@/components/layout/Navbar/Navbar'
import { cn } from '@/lib/utils/cn'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={cn(
          'relative h-full font-sans antialiased',
          inter.className
        )}>
        <main className="relative flex min-h-screen flex-col">
          <Navbar />
          <div className="flex-1 grow">{children}</div>
        </main>
      </body>
    </html>
  )
}
